export { default as NavBar } from './global/navbar/NavBar'
export { default as Blog } from './blog/Blog'
export { default as Features } from './features/Features'
export { default as Footer } from './global/footer/Footer'
export { default as Header } from './header/Header'
export { default as Possibility } from './possibility/Possibility'
export { default as WhatGPT3 } from './whatGPT3/WhatGPT3'